### ISSUE TITLE
Error On Startup After Updating Initial Config

### ISSUE THREAD

**Issue by MrMetacomCode** [JamieIsGeek/BungeecordDiscordSRV#2]
I couldn't find any documentation for this plugin anywhere so I just replaced the 2 things in the config.yml with what they're supposed to be and restarted the proxy. I then got this error:
```
00:22:57 [WARNING] Exception encountered when loading plugin: BungeecordDiscordSRV
java.lang.IllegalArgumentException: ID may not be empty
    at net.dv8tion.jda.internal.utils.Checks.notEmpty(Checks.java:77)
    at net.dv8tion.jda.api.utils.MiscUtil.parseSnowflake(MiscUtil.java:115)
    at net.dv8tion.jda.api.utils.cache.SnowflakeCacheView.getElementById(SnowflakeCacheView.java:59)
    at net.dv8tion.jda.api.JDA.getCategoryById(JDA.java:1525)
    at dev.jamieisgeek.bungeecorddiscordsrv.Models.DiscordBot.lambda$setupChannels$3(DiscordBot.java:76)
    at java.base/java.util.Map.forEach(Map.java:713)
    at dev.jamieisgeek.bungeecorddiscordsrv.Models.DiscordBot.setupChannels(DiscordBot.java:74)
    at dev.jamieisgeek.bungeecorddiscordsrv.Models.DiscordBot.<init>(DiscordBot.java:55)
    at dev.jamieisgeek.bungeecorddiscordsrv.BungeecordDiscordSRV.onEnable(BungeecordDiscordSRV.java:37)
    at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:266)
    at net.md_5.bungee.BungeeCord.start(BungeeCord.java:295)
    at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:67)
    at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)
```

Here is my config.yml file:
```
token: VERYLONGRANDOMTOKENSTUFFZ # Your bot token
category: 707992117942681631 # The category ID where the channels will be created
```

**Comment by JamieIsGeek** [comment]
Hey, I have been unable to reproduce this. Are you sure the bot is able to see the category provided?

**Comment by JamieIsGeek** [comment]
Was contacted by creator of #3 stating that wrapping the category id in quotes turning it into a string has solved this
