### ISSUE TITLE
Getting the Same Error as #2

### ISSUE THREAD

**Issue by shreyop200** [JamieIsGeek/BungeecordDiscordSRV#3]
everything is well done, and the bot is also given the perms to view the category

`08:20:27 [WARNING] Exception encountered when loading plugin: BungeecordDiscordSRV
java.lang.IllegalArgumentException: ID may not be empty
    at net.dv8tion.jda.internal.utils.Checks.notEmpty(Checks.java:77)
    at net.dv8tion.jda.api.utils.MiscUtil.parseSnowflake(MiscUtil.java:115)
    at net.dv8tion.jda.api.utils.cache.SnowflakeCacheView.getElementById(SnowflakeCacheView.java:59)
    at net.dv8tion.jda.api.JDA.getCategoryById(JDA.java:1525)
    at dev.jamieisgeek.bungeecorddiscordsrv.Models.DiscordBot.lambda$setupChannels$3(DiscordBot.java:76)
    at java.base/java.util.Map.forEach(Map.java:713)
    at dev.jamieisgeek.bungeecorddiscordsrv.Models.DiscordBot.setupChannels(DiscordBot.java:74)
    at dev.jamieisgeek.bungeecorddiscordsrv.Models.DiscordBot.<init>(DiscordBot.java:55)
    at dev.jamieisgeek.bungeecorddiscordsrv.BungeecordDiscordSRV.onEnable(BungeecordDiscordSRV.java:37)
    at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:266)
    at net.md_5.bungee.BungeeCord.start(BungeeCord.java:295)
    at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:67)
    at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)`

**Comment by JamieIsGeek** [comment]
Was contacted by creator of this stating that wrapping the category id in quotes turning it into a string has solved this
